//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice.ServiceReferencePhongThiNghiem {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePhongThiNghiem.WebServicePhongThiNghiemSoap")]
    public interface WebServicePhongThiNghiemSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThietBiByDM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetThietBiByDM();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThietBiByDM", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetThietBiByDMAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThietBiToiHan5Ngay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetThietBiToiHan5Ngay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThietBiToiHan5Ngay", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetThietBiToiHan5NgayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThietBiHetHan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetThietBiHetHan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThietBiHetHan", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetThietBiHetHanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBaiTNByIdGiaoVien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBaiTNByIdGiaoVien(int idgv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBaiTNByIdGiaoVien", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBaiTNByIdGiaoVienAsync(int idgv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePhongThiNghiemSoapChannel : Webservice.ServiceReferencePhongThiNghiem.WebServicePhongThiNghiemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePhongThiNghiemSoapClient : System.ServiceModel.ClientBase<Webservice.ServiceReferencePhongThiNghiem.WebServicePhongThiNghiemSoap>, Webservice.ServiceReferencePhongThiNghiem.WebServicePhongThiNghiemSoap {
        
        public WebServicePhongThiNghiemSoapClient() {
        }
        
        public WebServicePhongThiNghiemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePhongThiNghiemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePhongThiNghiemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePhongThiNghiemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet GetThietBiByDM() {
            return base.Channel.GetThietBiByDM();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetThietBiByDMAsync() {
            return base.Channel.GetThietBiByDMAsync();
        }
        
        public System.Data.DataSet GetThietBiToiHan5Ngay() {
            return base.Channel.GetThietBiToiHan5Ngay();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetThietBiToiHan5NgayAsync() {
            return base.Channel.GetThietBiToiHan5NgayAsync();
        }
        
        public System.Data.DataSet GetThietBiHetHan() {
            return base.Channel.GetThietBiHetHan();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetThietBiHetHanAsync() {
            return base.Channel.GetThietBiHetHanAsync();
        }
        
        public System.Data.DataSet GetBaiTNByIdGiaoVien(int idgv) {
            return base.Channel.GetBaiTNByIdGiaoVien(idgv);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBaiTNByIdGiaoVienAsync(int idgv) {
            return base.Channel.GetBaiTNByIdGiaoVienAsync(idgv);
        }
    }
}
